version: '2'
services:
    db: 
        image: mysql:5.7
        restart: always
        volumes:
          - ./configDB/initdb:/docker-entrypoint-initdb.d
          - ./dataDB/mysql:/var/lib/mysql
          - ./logsDB/mysql:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: ds_p5
            MYSQL_USER: grupo4
            MYSQL_PASSWORD: 1234
        ports:
            - "3307:3306"
    web: 
        build: ./
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
           - ./:/p5
        ports: 
          - "3001:3000"
        depends_on:
          - db
        links:
          - db
        environment:
          DB_USER: grupo4
          DB_NAME: ds_p5
          DB_PASSWORD: 1234
          DB_HOST: db
    phpmyadmin:
        image: phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: grupo4
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
          - ./configPMA/pma.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

